const commonjs = require("@rollup/plugin-commonjs");
const { babel } = require("@rollup/plugin-babel");
const license = require("rollup-plugin-license");

module.exports = {
  input: "src/index.js",
  external: [
    /@babel\/runtime/,
    "marked",
    "he",
    "react",
    "@react-pdf/renderer",
  ],
  output: [
    {
      file: "lib/marked-react-pdf.js",
      format: "cjs",
      name: "marked-react-pdf",
      exports: "default"
    },
    {
      file: "lib/marked-react-pdf.mjs",
      format: "esm",
      name: "marked-react-pdf"
    }
  ],
  plugins: [
    license({
      banner: `
DO NOT EDIT THIS FILE
The code in this file is generated from files in ./src/
`
    }),
    babel({
      babelHelpers: "runtime",
      plugins: [
        "@babel/plugin-transform-runtime",
        "@babel/plugin-transform-react-jsx"
      ]
    }),
    commonjs(),
  ]
};
